#include "EnemyShip.h"
#include "../../Core/Maths/Vector3.h"
#include "../../Core/Renderer/ConsoleColours.h"
#include <Windows.h>




/*
const int ENEMY_SPRITE_WIDTH = 5;
const int ENEMY_SPRITE_HEIGHT = 2;

CHAR_INFO EnemyShipSprite0[ENEMY_SPRITE_ANIMATION_FRAMES][ENEMY_SPRITE_WIDTH * ENEMY_SPRITE_HEIGHT] =
{
	{
		{ '/' ,FOREGROUND_WHITE },{ '_' ,FOREGROUND_WHITE },{ '_' ,FOREGROUND_WHITE } ,{ '_' ,FOREGROUND_WHITE },{ '\\' ,FOREGROUND_WHITE },
		{ 0 ,BACKGROUND_WHITE },{ '/' ,FOREGROUND_WHITE },{ 0 ,BACKGROUND_WHITE },{ '\\' ,FOREGROUND_WHITE },{ 0 ,BACKGROUND_WHITE },
	},
	{
		{ '\\' ,FOREGROUND_WHITE },{ '_' ,FOREGROUND_WHITE },{ '_' ,FOREGROUND_WHITE } ,{ '_' ,FOREGROUND_WHITE },{ '/' ,FOREGROUND_WHITE },
		{ 0 ,BACKGROUND_WHITE },{ '\\' ,FOREGROUND_WHITE },{ 'V' ,FOREGROUND_WHITE },{ '/' ,FOREGROUND_WHITE },{ 0 ,BACKGROUND_WHITE },
	},
	{
		{ 0 ,BACKGROUND_WHITE },{ '\\' , FOREGROUND_YELLOW },{ '|' ,FOREGROUND_YELLOW } ,{ '/' ,FOREGROUND_YELLOW },{ 0 ,BACKGROUND_WHITE },
		{ 0 ,BACKGROUND_WHITE },{ '/' , FOREGROUND_YELLOW },{ '|' ,FOREGROUND_YELLOW },{ '\\' ,FOREGROUND_YELLOW },{ 0 ,BACKGROUND_WHITE },
	},
	{
		{ 0 ,FOREGROUND_RED },{ '\\' , FOREGROUND_BRIGHT_RED },{ 0 ,FOREGROUND_BRIGHT_RED } ,{ '/' ,FOREGROUND_BRIGHT_RED },{ 0 ,FOREGROUND_BRIGHT_RED },
		{ 0 ,FOREGROUND_RED },{ '/' , FOREGROUND_BRIGHT_RED },{ 0 ,FOREGROUND_BRIGHT_RED },{ '\\' ,FOREGROUND_BRIGHT_RED },{ 0 ,FOREGROUND_BRIGHT_RED },
	},
};

CHAR_INFO EnemyShipSprite1[ENEMY_SPRITE_ANIMATION_FRAMES][ENEMY_SPRITE_WIDTH * ENEMY_SPRITE_HEIGHT] =
{
	{
		{ '|' ,FOREGROUND_WHITE },{ '_' ,FOREGROUND_WHITE },{ 1 ,FOREGROUND_WHITE } ,{ '_' ,FOREGROUND_WHITE },{ 0 ,BACKGROUND_WHITE },
		{ 0 ,BACKGROUND_WHITE },{ '|' ,FOREGROUND_WHITE },{ 0 ,BACKGROUND_WHITE },{ '|' ,FOREGROUND_WHITE },{ '|' ,FOREGROUND_WHITE },
	},
	{
		{ 0 ,BACKGROUND_WHITE },{ '_' ,FOREGROUND_WHITE },{ 1 ,FOREGROUND_WHITE } ,{ '_' ,FOREGROUND_WHITE },{ '|' ,FOREGROUND_WHITE },
		{ '|' ,FOREGROUND_WHITE },{ '|' ,FOREGROUND_WHITE },{ 0 ,BACKGROUND_WHITE },{ '|' ,FOREGROUND_WHITE },{ 0 ,BACKGROUND_WHITE },
	},
	{
		{ 0 ,BACKGROUND_WHITE },{ '\\' , FOREGROUND_YELLOW },{ '|' ,FOREGROUND_YELLOW } ,{ '/' ,FOREGROUND_YELLOW },{ 0 ,BACKGROUND_WHITE },
		{ 0 ,BACKGROUND_WHITE },{ '/' , FOREGROUND_YELLOW },{ '|' ,FOREGROUND_YELLOW },{ '\\' ,FOREGROUND_YELLOW },{ 0 ,BACKGROUND_WHITE },
	},
	{
		{ 0 ,FOREGROUND_RED },{ '\\' , FOREGROUND_BRIGHT_RED },{ 0 ,FOREGROUND_BRIGHT_RED } ,{ '/' ,FOREGROUND_BRIGHT_RED },{ 0 ,FOREGROUND_BRIGHT_RED },
		{ 0 ,FOREGROUND_RED },{ '/' , FOREGROUND_BRIGHT_RED },{ 0 ,FOREGROUND_BRIGHT_RED },{ '\\' ,FOREGROUND_BRIGHT_RED },{ 0 ,FOREGROUND_BRIGHT_RED },
	},
};
*/

const int ENEMY_SPRITE_WIDTH = 12;
const int ENEMY_SPRITE_HEIGHT = 8;

CHAR_INFO EnemyShipSprite0[ENEMY_SPRITE_ANIMATION_FRAMES][ENEMY_SPRITE_WIDTH * ENEMY_SPRITE_HEIGHT] =			//These chars are used to create the enemy sprites
{
	{
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
	},
	{
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
	},
	{
		{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
	},
	{
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
	},
};


CHAR_INFO EnemyShipSprite1[ENEMY_SPRITE_ANIMATION_FRAMES][ENEMY_SPRITE_WIDTH * ENEMY_SPRITE_HEIGHT] =
{
	{
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
	},
	{
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },
		{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BLUE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
	},

	{
		{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
	},
	{
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_BRIGHT_RED },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
		{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE } ,{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },{ ' ' ,BACKGROUND_WHITE },
	},

};


const int MOVEMENT_AMMOUNT = 1;								//This is the movement speed for the enemy

EnemyShip::EnemyShip()
:m_bInitialised(false)
,m_AnimationTimer(0.0f)
,m_Active(true)
,m_FireRate(0)
,m_ScoreValue(0)
{
}

EnemyShip::~EnemyShip()
{
}

void EnemyShip::Initialise(Vector2& position, int fireRate, int sprite, int scoreValue, float initialTime)		//Used to initialise all the enemies
{
	m_FireRate = fireRate;

	m_ScoreValue = scoreValue;

	m_AnimationTimer = initialTime;

	AnimatedSprite::Initialise(sprite == 0 ? &EnemyShipSprite0[0][0] : &EnemyShipSprite1[0][0], Vector3(ENEMY_SPRITE_WIDTH, ENEMY_SPRITE_HEIGHT, ENEMY_SPRITE_ANIMATION_FRAMES));

	Vector2 startPosition(position.x - (AnimatedSprite::GetSize().x / 2), position.y - (AnimatedSprite::GetSize().y / 2));
	SetPosition(startPosition);

	m_bInitialised = true;
}

bool EnemyShip::Update(float deltaTime)
{
	if (!m_bInitialised || !m_Active)
		return false;

	m_AnimationTimer += deltaTime;						//Used to calculate the time between each frame so they change equally 
	if (m_AnimationTimer >= 1.0f)
	{
		if (GetAnimationFrame() == 2)
		{
			m_AnimationTimer -= 0.15f;
			SetAnimationFrame(3);
		}
		else if (GetAnimationFrame() == 3)
		{
			SetAnimationFrame(1);
		}
		else
		{
			m_AnimationTimer -= 1.0f;
			SetAnimationFrame(GetAnimationFrame() == 0 ? 1 : 0);
		}

		return ShouldFire();
	}

	return false;
}

bool EnemyShip::ShouldFire()						//This tells the enemy when they can shoot after a cooldown
{
	bool shouldFire = false;
	int chance = rand() % 100;

	if (m_FireRate > chance)
	{
		shouldFire = true;
	}

	return shouldFire;
}

void EnemyShip::Render(ASCIIRenderer* pRenderer)				//This renders each frame
{
	if (!m_bInitialised || !m_Active)
		return;

	AnimatedSprite::Render(pRenderer);
}

void EnemyShip::MoveLeft()										//This gets the enemies to move left
{
	SetPosition(Vector2(GetPosition().x - MOVEMENT_AMMOUNT, GetPosition().y));
}

void EnemyShip::Explode()										//This gets called when the enemy is either hit with a missile or reaches the edge of the screen
{
	if (GetAnimationFrame() < 2)
	{

		m_AnimationTimer = 0.85f;
		SetAnimationFrame(2);
	}
}



